repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.5.13
  hooks:
      - id: uv-lock
        args: [--directory, pydockpack]
        files: ^(pydockpack/).*
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.6
  hooks:
    - id: ruff
    - id: ruff-format