[package]
name = "core-dockpack"
version = "0.1.0"
edition = "2021"
description = "A library for unpacking files from Docker images"
license = "MIT"

[dependencies]
tar = "0.4.40"
serde_json = "1.0.115"
flate2 = "1.0.28"
